export const DIRECTORY_1689 = [  
   {  
      "name":"Grace Covenant Church",
      "address":"1255 North Greenfield Rd, Gilbert, AZ 85234",
      "lat":"33.373407",
      "long":"-111.738757",
      "region":"Arizona",
      "website":"http://www.gccgilbert.com",
      "email":"PastorJohn@gracecovenantministry.org",
      "pastor":" Pastor John Giarrizzo",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"San Tan Reformed Baptist Church",
      "address":"France Brandon-Pickett Elementary School - 22076 East Village Loop Road, Queen Creek, AZ 85142",
      "lat":"33.233149",
      "long":"-111.609805",
      "region":"Arizona",
      "website":"http://santanreformedbaptistchurch.com",
      "email":"urquidez_frank@yahoo.com",
      "pastor":" Pastor Frank Urquidez",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Tucson Reformed Baptist Church",
      "address":"1603 S Eastside #209, Tucson, AZ 85710",
      "lat":"32.202448",
      "long":"-110.825611",
      "region":"Arizona",
      "website":"http://www.tucsonreformedbaptist.org",
      "email":"rcosby@me.com",
      "pastor":" Pastor Rob Cosby",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Centinela Baptist Church",
      "address":"4730 West 152nd St, Lawndale, CA 90260-1903",
      "lat":"33.893419",
      "long":"-118.360573",
      "region":"California",
      "website":"http://centinelabaptistchurch.com/",
      "email":"larrysmith43@prodigy.net",
      "pastor":" Pastor Larry Smith",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Christ Reformed Baptist Church",
      "address":"2210 E Vista Way, Vista, CA 92084",
      "lat":"33.233831",
      "long":"-117.226446",
      "region":"California",
      "website":"http://www.Christrbc.com",
      "email":"christrbcvista@gmail.com",
      "pastor":" Pastor Jason Walter",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Grace Reformed Baptist Church",
      "address":"1386 Carson Rd, Placerville, CA 95667",
      "lat":"38.7355",
      "long":"-120.783346",
      "region":"California",
      "website":"http://www.gracereformedbc.net",
      "email":"jeffolivergrbc@gmail.com",
      "pastor":" Pastor Jeff Oliver",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Grace Reformed Baptist Church",
      "address":"300 W Palmdale Blvd, Palmdale , CA 93551",
      "lat":"34.581342",
      "long":"-118.135284",
      "region":"California",
      "website":"http://grbcav.org",
      "email":"rb@rbap.net",
      "pastor":" Pastor Rich Barcellos",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Mariposa Reformed Baptist Church",
      "address":"4994 11th St, Mariposa, CA 95338",
      "lat":"37.489546",
      "long":"-119.969258",
      "region":"California",
      "website":"http://mariposachurch.org",
      "email":"dane.carlson@gmail.com",
      "pastor":" Pastor Dane Carlson",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Redeemer Reformed Baptist Church",
      "address":"1940 E Street, San Bernardino, CA 92408",
      "lat":"34.065463",
      "long":"-117.293757",
      "region":"California",
      "website":"http://Redeemer-RBC.com",
      "email":"jamassey@gmail.com",
      "pastor":" Jeffrey Massey",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Sovereign Grace Baptist Church",
      "address":"1168 East G St, Ontario, CA 91764",
      "lat":"34.070465",
      "long":"-117.629684",
      "region":"California",
      "website":"http://www.sgbc-ontario.us",
      "email":"Smarquedant@msn.com",
      "pastor":" Pastor Steve Marquedant",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Trinity Reformed Baptist Church",
      "address":"14407 E Rosecrans Ave, La Mirada, CA 90638",
      "lat":"33.902917",
      "long":"-118.024289",
      "region":"California",
      "website":"http://www.reformedbaptist.net",
      "email":"trbcsecretary@gmail.com",
      "pastor":" Pastor Sam Renihan",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Grace Reformed Baptist Church",
      "address":"1225 North High St, East Haven, CT 06512",
      "lat":"41.320202",
      "long":"-72.846643",
      "region":"Connecticut",
      "website":"http://www.grbcct.org",
      "email":"mxraines@aol.com",
      "pastor":" Pastor Mark Raines",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Grace Fellowship Church",
      "address":"11146 Ponder Rd, Lincoln, DE 19960",
      "lat":"38.835184",
      "long":"-75.395873",
      "region":"Delaware",
      "website":"http://www.gfcde.com",
      "email":"Jdundas@me.com",
      "pastor":" Pastor Jim Dundas",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Berean Baptist Church",
      "address":"Bellamy funeral Home - 3551 Jimmy LeeSmith Pkwy, Hiram, GA 30141",
      "lat":"33.897977",
      "long":"-84.767007",
      "region":"Georgia",
      "website":"http://www.bereanchurchps.org",
      "email":"pastorslate@gmail.com",
      "pastor":" Pastor Jery Slate, Jr",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Emmanuel Baptist Church",
      "address":"1618 Waycross Hwy, Jesup, GA 31545",
      "lat":"31.606404",
      "long":"-81.918054",
      "region":"Georgia",
      "website":"http://www.ebcjesup.org",
      "email":"ebc.jesup@att.net",
      "pastor":" Pastor Thomas Waters",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Redeemer Baptist Church",
      "address":"4652 Ayers Rd, Macon, GA 31210",
      "lat":"32.85812",
      "long":"-83.705269",
      "region":"Georgia",
      "website":"http://www.redeemer-baptist.org",
      "email":"efreel@hotmail.com",
      "pastor":" Pastor Eric Freel",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Trinity Reformed Baptist Church",
      "address":"543 Colwell Rd, Jackson, GA 30233",
      "lat":"33.23802",
      "long":"-84.068221",
      "region":"Georgia",
      "website":"http://www.trinityrbc.org",
      "email":"brandonfsmith73@gmail.com",
      "pastor":" Pastor Brandon Smith",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Port Cities Reformed Baptist Church",
      "address":"1424 Main St, Lewiston, ID 83501",
      "lat":"46.417708",
      "long":"-117.012382",
      "region":"Idaho",
      "website":"http://www.portcitiesreformed.org",
      "email":"mskelly@cableone.net",
      "pastor":" Pastor Michael Kelly",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Grace Reformed Baptist Church",
      "address":"6310 Guilford Rd, Rockford, IL 61107",
      "lat":"42.28381",
      "long":"-88.993774",
      "region":"Illinois",
      "website":"http://www.grbcrockford.org",
      "email":"grbcrockford@juno.com",
      "pastor":" Pastor Dale Smith",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Hope Reformed Baptist Church",
      "address":"Old St. Paul's Church - 6200 Vollmer Rd., Matteson, IL 60443",
      "lat":"41.526587",
      "long":"-87.765835",
      "region":"Illinois",
      "website":"",
      "email":"yoder.john.e@gmail.com",
      "pastor":" Pastor John Yoder",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Sycamore Baptist Church",
      "address":"5323 180th St North, East Moline, IL 61244",
      "lat":"41.572728",
      "long":"-90.368218",
      "region":"Illinois",
      "website":"http://www.sycamorebaptistchurch.com",
      "email":"chuckrennie2@gmail.com",
      "pastor":" Pastor Chuck Rennie",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Cornerstone Fellowship Church",
      "address":"3665 Bell Rd, Newburgh, IN 47630",
      "lat":"37.98159",
      "long":"-87.405391",
      "region":"Indiana",
      "website":"http://www.cornerstone-fellowship.org",
      "email":"bill-francis@att.net",
      "pastor":" Pastor Bill Francise",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Grace Reformed Baptist Church",
      "address":"115 Gunder Rd NE, Elkader, IA 52043",
      "lat":"42.867699",
      "long":"-91.399018",
      "region":"Iowa",
      "website":"http://www.sermonaudio.com/source_detail.asp?sourceid=grbcclaytoncounty",
      "email":"gracereformedbaptistchurch@gmail.com",
      "pastor":" Elder Reece Klink",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Reformed Baptist Church of Kansas City",
      "address":"24450 West 83rd St, Lenexa, KS 66227",
      "lat":"38.978972",
      "long":"-94.871",
      "region":"Kansas",
      "website":"http://www.reformedbaptistkc.org",
      "email":"reformedbaptistkc@hotmail.com",
      "pastor":" Pastor Martin Nish",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Grace Reformed Baptist Church",
      "address":"1501 East 26th Street, Owensboro, KY 42303",
      "lat":"37.752293",
      "long":"-87.091346",
      "region":"Kentucky",
      "website":"http://www.grbco.org",
      "email":"pastorsam@grbco.org",
      "pastor":" Pastor Sam Waldron",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"First Baptist Church",
      "address":"12329 Jackson St, Clinton, LA 70722",
      "lat":"30.864749",
      "long":"-91.015625",
      "region":"Louisiana",
      "website":"http://www.fbcclintonla.com",
      "email":"tomhicksjr@gmail.com",
      "pastor":" Dr. Tom Hicks; Dr. Fred Malone",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Heritage Baptist Church",
      "address":"2801 Creswell Ave, Shreveport, LA 71104",
      "lat":"32.484208",
      "long":"-93.741486",
      "region":"Louisiana",
      "website":"http://www.hbcshreveport.com",
      "email":"earlmblackburn@bellsouth.net",
      "pastor":" Pastor Earl Blackburn",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Providence Baptist Church",
      "address":"53 Hammock Lane, Ball, LA 71405",
      "lat":"31.430248",
      "long":"-92.407369",
      "region":"Louisiana",
      "website":"",
      "email":"provbaptist@gmail.com",
      "pastor":" Pastor William Avants",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Trinity Baptist Church",
      "address":"7125 Goodwood Ave, Baton Rouge, LA 70806",
      "lat":"30.442044",
      "long":"-91.115865",
      "region":"Louisiana",
      "website":"http://www.trinitybaptistreformed.org",
      "email":"trinityrbc@bellsouth.net",
      "pastor":" Pastor Dale Crawford",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Grace Reformed Baptist Church",
      "address":"People Plus - 35 Union St, Brunswick, ME 04011",
      "lat":"43.915295",
      "long":"-69.968222",
      "region":"Maine",
      "website":"http://www.grbcme.org",
      "email":"mrenihan@grbcme.org",
      "pastor":" Pastor Micah Renihan",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Providence Baptist Church",
      "address":"40 Main Street, Walkersville, MD 21793",
      "lat":"39.485963",
      "long":"-77.350791",
      "region":"Maryland",
      "website":"http://pbcofwalkersville.org",
      "email":"mintorobert@gmail.com",
      "pastor":" Robert Minto",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Austin Square Baptist Church",
      "address":"10 Keslar Ave, Lynn, MA 01905",
      "lat":"42.462819",
      "long":"-70.98065",
      "region":"Massachusetts",
      "website":"http://austinsquarechurch.com",
      "email":"spw3760@gmail.com",
      "pastor":" Pastor Steven Wilfert",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Heritage Baptist Church",
      "address":"59 Blackstone River Rd, Worcester, MA 01607",
      "lat":"42.232119",
      "long":"-71.793751",
      "region":"Massachusetts",
      "website":"http://www.hbcma.org",
      "email":"mike_renihan@yahoo.com",
      "pastor":" Pastor Mike Renihan",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Grace Baptist Church",
      "address":"5536 Ridgewood Rd, Jackson, MS 39211",
      "lat":"32.378259",
      "long":"-90.141087",
      "region":"Mississippi",
      "website":"http://www.gracejackson.net",
      "email":"pastorwinn@bellsouth.net",
      "pastor":" Pastor Thomas Winn",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Santa Teresa Baptist Church",
      "address":"5750 McNutt Rd, Santa Teresa, NM 88008",
      "lat":"31.86603",
      "long":"-106.647704",
      "region":"New Mexico",
      "website":"http://www.stbcweb.org",
      "email":"pastor@stbcweb.org",
      "pastor":" Pastor Dave Hendrickx",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Hope Reformed Baptist Church",
      "address":"3239 Rt 112, Bldg 8, Medford, NY 11763",
      "lat":"40.840748",
      "long":"72.996554",
      "region":"New York",
      "website":"http://www.hopereformedli.net",
      "email":"rjensen@hopereformedli.net",
      "pastor":" Pastor Rich Jensen",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Community Baptist Church",
      "address":"3535 25th St South, Fargo, ND 58104",
      "lat":"46.82619",
      "long":"-96.820763",
      "region":"North Dakota",
      "website":"http://www.cbcfargo.com",
      "email":"douglasvan@mac.com",
      "pastor":" Pastor Douglas VanderMeulen",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Grace Covenant Church",
      "address":"24430 Nobottom Rd, Olmstead Township, OH 44138",
      "lat":"41.384271",
      "long":"-81.878323",
      "region":"Ohio",
      "website":"http://www.gracecovenantcleveland.com",
      "email":"fpugh@sbcglobal.net",
      "pastor":" Pastor Fred Pugh",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Elm Street Baptist Church",
      "address":"1150 Elm St, Sweet Home, OR 97386",
      "lat":"44.392173",
      "long":"-122.729892",
      "region":"Oregon",
      "website":"http://www.elmstreetbaptistchurch.org",
      "email":"specbird@peak.org",
      "pastor":" Pastor Ralph Anderegg",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Grace Baptist Church",
      "address":"777 W North St, Carlisle, PA 17013",
      "lat":"40.206487",
      "long":"-77.207232",
      "region":"Pennsylvania",
      "website":"http://www.gracebaptistcarlisle.org",
      "email":"gbc@gracebaptistcarlisle.org",
      "pastor":" Elder Tom Richwine",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Grace Baptist Church",
      "address":"2475 McCleary Dr, Chambersburg, PA 17201",
      "lat":"39.970189",
      "long":"-77.632623",
      "region":"Pennsylvania",
      "website":"http://www.gbcchambersburg.org",
      "email":"charrisgbc@embarqmail.com",
      "pastor":" Pastor Craig Harris",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Reibers Reformed Baptist Church",
      "address":"180 Reibers Church Rd, Shermans Dale, PA 17090",
      "lat":"40.312614",
      "long":"-77.2291",
      "region":"Pennsylvania",
      "website":"http://www.reiberschurch.com",
      "email":"joie@pa.net",
      "pastor":" Pastor Charles Fitzpatrick",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Christ Reformed Baptist Church",
      "address":"901 Scenic Hwy, Lookout Mountain, TN 37350",
      "lat":"34.990286",
      "long":"-85.35336",
      "region":"Tennessee",
      "website":"http://www.crbchattanooga.org/",
      "email":"crbchattanooga@gmail.com",
      "pastor":" Pastor Nathan White",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Covenant Baptist Church",
      "address":"2201 Old Russellville Pike, Clarksville, TN 37040",
      "lat":"36.565833",
      "long":"-87.301778",
      "region":"Tennessee",
      "website":"http://www.covenantbaptistclarksville.com/",
      "email":"info@covenantbaptistclarksville.com",
      "pastor":" Pastor John Miller",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Covenant Reformed Baptist Church",
      "address":"Holiday Inn Longview North 300 Tuttle Cir, Longview, TX 75605 -",
      "lat":"32.544696",
      "long":"-94.752644",
      "region":"Texas",
      "website":"http://covenantreformedbaptistchurch.com/",
      "email":"imputationist@gmail.com",
      "pastor":" Pastor Dave Randall",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Emmanuel Reformed Baptist Church",
      "address":"5030 East State Highway 29, Georgetown, TX 78626",
      "lat":"30.638071",
      "long":"-97.538049",
      "region":"Texas",
      "website":"http://emmanuelrbc.com",
      "email":"bcurley1689@gmail.com",
      "pastor":" Bob Curly & Steve Garrick",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Faith Community Baptist Church",
      "address":"1701 Wind Star Way, Fort Worth, TX 76108",
      "lat":"32.743773",
      "long":"-97.497793",
      "region":"Texas",
      "website":"http://www.faithcommunitybaptistchurch.com",
      "email":"fcbchurch@sbcglobal.net",
      "pastor":" Pastor Jason Montgomery",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Grace Baptist Church",
      "address":"375 W Main St, Van, TX 75790",
      "lat":"32.524148",
      "long":"-95.64113",
      "region":"Texas",
      "website":"http://www.gracebaptistvan.com",
      "email":"pastorcliff55@gmail.com",
      "pastor":" Pastor Cliff Cooper",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Grace Covenant Baptist Church",
      "address":"5010 W Danville Rd, Willis, TX 77318",
      "lat":"30.490494",
      "long":"-95.497991",
      "region":"Texas",
      "website":"http://www.gcbcwillis.org",
      "email":"info@gcbcwillis.org",
      "pastor":" Pastor David Dykstra",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Heritage Baptist Church",
      "address":"201 E Broad St, Mansfield, TX 76063",
      "lat":"32.563893",
      "long":"-97.140156",
      "region":"Texas",
      "website":"http://www.reformedbaptist.org",
      "email":"larryv325@gmail.com",
      "pastor":" Pastor Larry Vincent",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Waco Family Baptist Church",
      "address":"219 Country Rd 329, Rosebud, TX 76570",
      "lat":"31.130416",
      "long":"-96.891328",
      "region":"Texas",
      "website":"http://www.wacofamily.com",
      "email":"pastor@wacofamily.com",
      "pastor":" Pastor Todd Gill",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Redeeming Grace Baptist Church",
      "address":"8245 Buckley Hall Rd, Hudgins, VA 23176",
      "lat":"37.47072",
      "long":"-76.326414",
      "region":"Virginia",
      "website":"http://www.redeeming-grace.org",
      "email":"van.loomis@gmail.com",
      "pastor":" Pastor Van Loomis",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"West Suffolk Baptist Church",
      "address":"1001 Kenyon Ct, Suffolk, VA 23434",
      "lat":"36.72533",
      "long":"-76.656991",
      "region":"Virginia",
      "website":"http://www.graceforsuffolk.org",
      "email":"pastorscofield@gmail.com",
      "pastor":" Pastor Ben Scofield",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Providence Reformed Baptist Church",
      "address":"7002 St West, University Place, WA 98466",
      "lat":"47.234485",
      "long":"-122.556173",
      "region":"Washington",
      "website":"http://prbc-wa.org",
      "email":"tlyonup@harbornet.com",
      "pastor":" Pastor Tom Lyon",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Trinity Reformed Baptist Church",
      "address":"315 3rd Ave S, Kirkland, WA 98033",
      "lat":"47.673104",
      "long":"-122.201659",
      "region":"Washington",
      "website":"http://www.trinityreformedbaptist.com",
      "email":"donrlindblad@gmail.com",
      "pastor":" Pastors Don Lindblad & Stefan Lindblad",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Christ Reformed Baptist Church",
      "address":"12219 W Janesville Rd, Hales Corners, WI 32130",
      "lat":"42.933491",
      "long":"-88.068389",
      "region":"Wisconsin",
      "website":"http://www.crbc.us",
      "email":"",
      "pastor":" Bill Halliburton, Elder",
      "confession":"1689 Confessional",
      "lastUpdated":"5/28/2017"
   },
   {  
      "name":"Grace Baptist Church",
      "address":"122 Walnut Street, Madison, AL 35758",
      "lat":"34.751726",
      "long":"-86.746557",
      "region":"Alabama",
      "website":"http://www.gbcmadison-al.com/",
      "email":"pastor@gbcmadison-al.com",
      "pastor":"Dean Olive",
      "confession":"1689 Confessional (with some revisions)",
      "lastUpdated":"5/28/2017"
   }
];