export const DIRECTORY_1689 = [  
    {  
        "name":"Providence Baptist Church",
        "address":"1355 Douglass Road, Huntsville, AL 35806",
        "lat":"34.801132",
        "long":"-86.733387",
        "region":"Alabama, Huntsville",
        "website":"http://providencebaptist.us/",
        "email":"pbcoffice1355@gmail.com",
        "pastor":"Blair Waddell",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Grace Baptist Church",
        "address":"122 Walnut Street, Madison, AL 35758",
        "lat":"34.751726",
        "long":"-86.746557",
        "region":"Alabama, Madison",
        "website":"http://www.gbcmadison-al.com/",
        "email":"pastor@gbcmadison-al.com",
        "pastor":"Dean Olive",
        "confession":"1689 Confessional (with some revisions)",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Grace Covenant Church",
        "address":"1255 North Greenfield Rd, Gilbert, AZ 85234",
        "lat":"33.373407",
        "long":"-111.738757",
        "region":"Arizona, Gilbert",
        "website":"http://www.gccgilbert.com",
        "email":"PastorJohn@gracecovenantministry.org",
        "pastor":" Pastor John Giarrizzo",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"San Tan Reformed Baptist Church",
        "address":"France Brandon-Pickett Elementary School - 22076 East Village Loop Road, Queen Creek, AZ 85142",
        "lat":"33.233149",
        "long":"-111.609805",
        "region":"Arizona, Queen Creek",
        "website":"http://santanreformedbaptistchurch.com",
        "email":"urquidez_frank@yahoo.com",
        "pastor":" Pastor Frank Urquidez",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Tucson Reformed Baptist Church",
        "address":"1603 S Eastside #209, Tucson, AZ 85710",
        "lat":"32.202448",
        "long":"-110.825611",
        "region":"Arizona, Tucson",
        "website":"http://www.tucsonreformedbaptist.org",
        "email":"rcosby@me.com",
        "pastor":" Pastor Rob Cosby",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Trinity Reformed Baptist Church",
        "address":"14407 E Rosecrans Ave, La Mirada, CA 90638",
        "lat":"33.902917",
        "long":"-118.024289",
        "region":"California, La Mirada",
        "website":"http://www.reformedbaptist.net",
        "email":"trbcsecretary@gmail.com",
        "pastor":" Pastor Sam Renihan",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Centinela Baptist Church",
        "address":"4730 West 152nd St, Lawndale, CA 90260-1903",
        "lat":"33.893419",
        "long":"-118.360573",
        "region":"California, Lawndale",
        "website":"http://centinelabaptistchurch.com/",
        "email":"larrysmith43@prodigy.net",
        "pastor":" Pastor Larry Smith",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Mariposa Reformed Baptist Church",
        "address":"4994 11th St, Mariposa, CA 95338",
        "lat":"37.489546",
        "long":"-119.969258",
        "region":"California, Mariposa",
        "website":"http://mariposachurch.org",
        "email":"dane.carlson@gmail.com",
        "pastor":" Pastor Dane Carlson",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Sovereign Grace Baptist Church",
        "address":"1168 East G St, Ontario, CA 91764",
        "lat":"34.070465",
        "long":"-117.629684",
        "region":"California, Ontario",
        "website":"http://www.sgbc-ontario.us",
        "email":"Smarquedant@msn.com",
        "pastor":" Pastor Steve Marquedant",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Grace Reformed Baptist Church",
        "address":"300 W Palmdale Blvd, Palmdale , CA 93551",
        "lat":"34.581342",
        "long":"-118.135284",
        "region":"California, Palmdale",
        "website":"http://grbcav.org",
        "email":"rb@rbap.net",
        "pastor":" Pastor Rich Barcellos",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Grace Reformed Baptist Church",
        "address":"1386 Carson Rd, Placerville, CA 95667",
        "lat":"38.7355",
        "long":"-120.783346",
        "region":"California, Placerville",
        "website":"http://www.gracereformedbc.net",
        "email":"jeffolivergrbc@gmail.com",
        "pastor":" Pastor Jeff Oliver",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Redeemer Reformed Baptist Church",
        "address":"1940 E Street, San Bernardino, CA 92408",
        "lat":"34.065463",
        "long":"-117.293757",
        "region":"California, San Bernardino",
        "website":"http://Redeemer-RBC.com",
        "email":"jamassey@gmail.com",
        "pastor":" Jeffrey Massey",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Christ Reformed Baptist Church",
        "address":"2210 E Vista Way, Vista, CA 92084",
        "lat":"33.233831",
        "long":"-117.226446",
        "region":"California, Vista",
        "website":"http://www.Christrbc.com",
        "email":"christrbcvista@gmail.com",
        "pastor":" Pastor Jason Walter",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Grace Reformed Baptist Church",
        "address":"1225 North High St, East Haven, CT 06512",
        "lat":"41.320202",
        "long":"-72.846643",
        "region":"Connecticut, East Haven",
        "website":"http://www.grbcct.org",
        "email":"mxraines@aol.com",
        "pastor":" Pastor Mark Raines",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Grace Fellowship Church",
        "address":"11146 Ponder Rd, Lincoln, DE 19960",
        "lat":"38.835184",
        "long":"-75.395873",
        "region":"Delaware, Lincoln",
        "website":"http://www.gfcde.com",
        "email":"Jdundas@me.com",
        "pastor":" Pastor Jim Dundas",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Berean Baptist Church",
        "address":"Bellamy funeral Home - 3551 Jimmy LeeSmith Pkwy, Hiram, GA 30141",
        "lat":"33.897977",
        "long":"-84.767007",
        "region":"Georgia, Hiram",
        "website":"http://www.bereanchurchps.org",
        "email":"pastorslate@gmail.com",
        "pastor":" Pastor Jery Slate, Jr",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Trinity Reformed Baptist Church",
        "address":"543 Colwell Rd, Jackson, GA 30233",
        "lat":"33.23802",
        "long":"-84.068221",
        "region":"Georgia, Jackson",
        "website":"http://www.trinityrbc.org",
        "email":"brandonfsmith73@gmail.com",
        "pastor":" Pastor Brandon Smith",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Emmanuel Baptist Church",
        "address":"1618 Waycross Hwy, Jesup, GA 31545",
        "lat":"31.606404",
        "long":"-81.918054",
        "region":"Georgia, Jesup",
        "website":"http://www.ebcjesup.org",
        "email":"ebc.jesup@att.net",
        "pastor":" Pastor Thomas Waters",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Redeemer Baptist Church",
        "address":"4652 Ayers Rd, Macon, GA 31210",
        "lat":"32.85812",
        "long":"-83.705269",
        "region":"Georgia, Macon",
        "website":"http://www.redeemer-baptist.org",
        "email":"efreel@hotmail.com",
        "pastor":" Pastor Eric Freel",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Port Cities Reformed Baptist Church",
        "address":"1424 Main St, Lewiston, ID 83501",
        "lat":"46.417708",
        "long":"-117.012382",
        "region":"Idaho, Lewiston",
        "website":"http://www.portcitiesreformed.org",
        "email":"mskelly@cableone.net",
        "pastor":" Pastor Michael Kelly",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Sycamore Baptist Church",
        "address":"5323 180th St North, East Moline, IL 61244",
        "lat":"41.572728",
        "long":"-90.368218",
        "region":"Illinois, East Moline",
        "website":"http://www.sycamorebaptistchurch.com",
        "email":"chuckrennie2@gmail.com",
        "pastor":" Pastor Chuck Rennie",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Hope Reformed Baptist Church",
        "address":"Old St. Paul's Church - 6200 Vollmer Rd., Matteson, IL 60443",
        "lat":"41.526587",
        "long":"-87.765835",
        "region":"Illinois, Matteson",
        "website":"",
        "email":"yoder.john.e@gmail.com",
        "pastor":" Pastor John Yoder",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Grace Reformed Baptist Church",
        "address":"6310 Guilford Rd, Rockford, IL 61107",
        "lat":"42.28381",
        "long":"-88.993774",
        "region":"Illinois, Rockford",
        "website":"http://www.grbcrockford.org",
        "email":"grbcrockford@juno.com",
        "pastor":" Pastor Dale Smith",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Cornerstone Fellowship Church",
        "address":"3665 Bell Rd, Newburgh, IN 47630",
        "lat":"37.98159",
        "long":"-87.405391",
        "region":"Indiana, Newburgh",
        "website":"http://www.cornerstone-fellowship.org",
        "email":"bill-francis@att.net",
        "pastor":" Pastor Bill Francise",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Grace Reformed Baptist Church",
        "address":"115 Gunder Rd NE, Elkader, IA 52043",
        "lat":"42.867699",
        "long":"-91.399018",
        "region":"Iowa, Elkader",
        "website":"http://www.sermonaudio.com/source_detail.asp?sourceid=grbcclaytoncounty",
        "email":"gracereformedbaptistchurch@gmail.com",
        "pastor":" Elder Reece Klink",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Reformed Baptist Church of Kansas City",
        "address":"24450 West 83rd St, Lenexa, KS 66227",
        "lat":"38.978972",
        "long":"-94.871",
        "region":"Kansas, Lenexa",
        "website":"http://www.reformedbaptistkc.org",
        "email":"reformedbaptistkc@hotmail.com",
        "pastor":" Pastor Martin Nish",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Grace Reformed Baptist Church",
        "address":"1501 East 26th Street, Owensboro, KY 42303",
        "lat":"37.752293",
        "long":"-87.091346",
        "region":"Kentucky, Owesboro",
        "website":"http://www.grbco.org",
        "email":"pastorsam@grbco.org",
        "pastor":" Pastor Sam Waldron",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Providence Baptist Church",
        "address":"53 Hammock Lane, Ball, LA 71405",
        "lat":"31.430248",
        "long":"-92.407369",
        "region":"Louisiana, Ball",
        "website":"",
        "email":"provbaptist@gmail.com",
        "pastor":" Pastor William Avants",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Trinity Baptist Church",
        "address":"7125 Goodwood Ave, Baton Rouge, LA 70806",
        "lat":"30.442044",
        "long":"-91.115865",
        "region":"Louisiana, Baton Rouge",
        "website":"http://www.trinitybaptistreformed.org",
        "email":"trinityrbc@bellsouth.net",
        "pastor":" Pastor Dale Crawford",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"First Baptist Church",
        "address":"12329 Jackson St, Clinton, LA 70722",
        "lat":"30.864749",
        "long":"-91.015625",
        "region":"Louisiana, Clinton",
        "website":"http://www.fbcclintonla.com",
        "email":"tomhicksjr@gmail.com",
        "pastor":" Dr. Tom Hicks; Dr. Fred Malone",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Heritage Baptist Church",
        "address":"2801 Creswell Ave, Shreveport, LA 71104",
        "lat":"32.484208",
        "long":"-93.741486",
        "region":"Louisiana, Shreveport",
        "website":"http://www.hbcshreveport.com",
        "email":"earlmblackburn@bellsouth.net",
        "pastor":" Pastor Earl Blackburn",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Grace Reformed Baptist Church",
        "address":"People Plus - 35 Union St, Brunswick, ME 04011",
        "lat":"43.915295",
        "long":"-69.968222",
        "region":"Maine, Brunswick",
        "website":"http://www.grbcme.org",
        "email":"mrenihan@grbcme.org",
        "pastor":" Pastor Micah Renihan",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Providence Baptist Church",
        "address":"40 Main Street, Walkersville, MD 21793",
        "lat":"39.485963",
        "long":"-77.350791",
        "region":"Maryland, Walkersville",
        "website":"http://pbcofwalkersville.org",
        "email":"mintorobert@gmail.com",
        "pastor":" Robert Minto",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Austin Square Baptist Church",
        "address":"10 Keslar Ave, Lynn, MA 01905",
        "lat":"42.462819",
        "long":"-70.98065",
        "region":"Massachusetts, Lynn",
        "website":"http://austinsquarechurch.com",
        "email":"spw3760@gmail.com",
        "pastor":" Pastor Steven Wilfert",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Heritage Baptist Church",
        "address":"59 Blackstone River Rd, Worcester, MA 01607",
        "lat":"42.232119",
        "long":"-71.793751",
        "region":"Massachusetts, Worcester",
        "website":"http://www.hbcma.org",
        "email":"mike_renihan@yahoo.com",
        "pastor":" Pastor Mike Renihan",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Grace Baptist Church",
        "address":"5536 Ridgewood Rd, Jackson, MS 39211",
        "lat":"32.378259",
        "long":"-90.141087",
        "region":"Mississippi, Jackson",
        "website":"http://www.gracejackson.net",
        "email":"pastorwinn@bellsouth.net",
        "pastor":" Pastor Thomas Winn",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Santa Teresa Baptist Church",
        "address":"5750 McNutt Rd, Santa Teresa, NM 88008",
        "lat":"31.86603",
        "long":"-106.647704",
        "region":"New Mexico, Santa Teresa",
        "website":"http://www.stbcweb.org",
        "email":"pastor@stbcweb.org",
        "pastor":" Pastor Dave Hendrickx",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Hope Reformed Baptist Church",
        "address":"3239 Rt 112, Bldg 8, Medford, NY 11763",
        "lat":"40.840748",
        "long":"72.996554",
        "region":"New York, Medford",
        "website":"http://www.hopereformedli.net",
        "email":"rjensen@hopereformedli.net",
        "pastor":" Pastor Rich Jensen",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Community Baptist Church",
        "address":"3535 25th St South, Fargo, ND 58104",
        "lat":"46.82619",
        "long":"-96.820763",
        "region":"North Dakota, Fargo",
        "website":"http://www.cbcfargo.com",
        "email":"douglasvan@mac.com",
        "pastor":" Pastor Douglas VanderMeulen",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Grace Covenant Church",
        "address":"24430 Nobottom Rd, Olmstead Township, OH 44138",
        "lat":"41.384271",
        "long":"-81.878323",
        "region":"Ohio, Olmstead Township",
        "website":"http://www.gracecovenantcleveland.com",
        "email":"fpugh@sbcglobal.net",
        "pastor":" Pastor Fred Pugh",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Elm Street Baptist Church",
        "address":"1150 Elm St, Sweet Home, OR 97386",
        "lat":"44.392173",
        "long":"-122.729892",
        "region":"Oregon, Sweet Home",
        "website":"http://www.elmstreetbaptistchurch.org",
        "email":"specbird@peak.org",
        "pastor":" Pastor Ralph Anderegg",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Grace Baptist Church",
        "address":"777 W North St, Carlisle, PA 17013",
        "lat":"40.206487",
        "long":"-77.207232",
        "region":"Pennsylvania, Carlisle",
        "website":"http://www.gracebaptistcarlisle.org",
        "email":"gbc@gracebaptistcarlisle.org",
        "pastor":" Elder Tom Richwine",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Grace Baptist Church",
        "address":"2475 McCleary Dr, Chambersburg, PA 17201",
        "lat":"39.970189",
        "long":"-77.632623",
        "region":"Pennsylvania, Chambersburg",
        "website":"http://www.gbcchambersburg.org",
        "email":"charrisgbc@embarqmail.com",
        "pastor":" Pastor Craig Harris",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Reibers Reformed Baptist Church",
        "address":"180 Reibers Church Rd, Shermans Dale, PA 17090",
        "lat":"40.312614",
        "long":"-77.2291",
        "region":"Pennsylvania, Shermans Dale",
        "website":"http://www.reiberschurch.com",
        "email":"joie@pa.net",
        "pastor":" Pastor Charles Fitzpatrick",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Covenant Baptist Church",
        "address":"2201 Old Russellville Pike, Clarksville, TN 37040",
        "lat":"36.565833",
        "long":"-87.301778",
        "region":"Tennessee, Clarksville",
        "website":"http://www.covenantbaptistclarksville.com/",
        "email":"info@covenantbaptistclarksville.com",
        "pastor":" Pastor John Miller",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Christ Reformed Baptist Church",
        "address":"901 Scenic Hwy, Lookout Mountain, TN 37350",
        "lat":"34.990286",
        "long":"-85.35336",
        "region":"Tennessee, Lookout Mountain",
        "website":"http://www.crbchattanooga.org/",
        "email":"crbchattanooga@gmail.com",
        "pastor":" Pastor Nathan White",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Faith Community Baptist Church",
        "address":"1701 Wind Star Way, Fort Worth, TX 76108",
        "lat":"32.743773",
        "long":"-97.497793",
        "region":"Texas, Fort Worth",
        "website":"http://www.faithcommunitybaptistchurch.com",
        "email":"fcbchurch@sbcglobal.net",
        "pastor":" Pastor Jason Montgomery",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Emmanuel Reformed Baptist Church",
        "address":"5030 East State Highway 29, Georgetown, TX 78626",
        "lat":"30.638071",
        "long":"-97.538049",
        "region":"Texas, Georgetown",
        "website":"http://emmanuelrbc.com",
        "email":"bcurley1689@gmail.com",
        "pastor":" Bob Curly & Steve Garrick",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Covenant Reformed Baptist Church",
        "address":"Holiday Inn Longview North 300 Tuttle Cir, Longview, TX 75605 -",
        "lat":"32.544696",
        "long":"-94.752644",
        "region":"Texas, Longview",
        "website":"http://covenantreformedbaptistchurch.com/",
        "email":"imputationist@gmail.com",
        "pastor":" Pastor Dave Randall",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Heritage Baptist Church",
        "address":"201 E Broad St, Mansfield, TX 76063",
        "lat":"32.563893",
        "long":"-97.140156",
        "region":"Texas, Mansfield",
        "website":"http://www.reformedbaptist.org",
        "email":"larryv325@gmail.com",
        "pastor":" Pastor Larry Vincent",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Waco Family Baptist Church",
        "address":"219 Country Rd 329, Rosebud, TX 76570",
        "lat":"31.130416",
        "long":"-96.891328",
        "region":"Texas, Rosebud",
        "website":"http://www.wacofamily.com",
        "email":"pastor@wacofamily.com",
        "pastor":" Pastor Todd Gill",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Grace Baptist Church",
        "address":"375 W Main St, Van, TX 75790",
        "lat":"32.524148",
        "long":"-95.64113",
        "region":"Texas, Van",
        "website":"http://www.gracebaptistvan.com",
        "email":"pastorcliff55@gmail.com",
        "pastor":" Pastor Cliff Cooper",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Grace Covenant Baptist Church",
        "address":"5010 W Danville Rd, Willis, TX 77318",
        "lat":"30.490494",
        "long":"-95.497991",
        "region":"Texas, Willis",
        "website":"http://www.gcbcwillis.org",
        "email":"info@gcbcwillis.org",
        "pastor":" Pastor David Dykstra",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Redeeming Grace Baptist Church",
        "address":"8245 Buckley Hall Rd, Hudgins, VA 23176",
        "lat":"37.47072",
        "long":"-76.326414",
        "region":"Virginia, Hudgins",
        "website":"http://www.redeeming-grace.org",
        "email":"van.loomis@gmail.com",
        "pastor":" Pastor Van Loomis",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"West Suffolk Baptist Church",
        "address":"1001 Kenyon Ct, Suffolk, VA 23434",
        "lat":"36.72533",
        "long":"-76.656991",
        "region":"Virginia, Suffolk",
        "website":"http://www.graceforsuffolk.org",
        "email":"pastorscofield@gmail.com",
        "pastor":" Pastor Ben Scofield",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Trinity Reformed Baptist Church",
        "address":"315 3rd Ave S, Kirkland, WA 98033",
        "lat":"47.673104",
        "long":"-122.201659",
        "region":"Washington, Kirkland",
        "website":"http://www.trinityreformedbaptist.com",
        "email":"donrlindblad@gmail.com",
        "pastor":" Pastors Don Lindblad & Stefan Lindblad",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Providence Reformed Baptist Church",
        "address":"7002 St West, University Place, WA 98466",
        "lat":"47.234485",
        "long":"-122.556173",
        "region":"Washington, University Place",
        "website":"http://prbc-wa.org",
        "email":"tlyonup@harbornet.com",
        "pastor":" Pastor Tom Lyon",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Christ Reformed Baptist Church",
        "address":"12219 W Janesville Rd, Hales Corners, WI 32130",
        "lat":"42.933491",
        "long":"-88.068389",
        "region":"Wisconsin, Hales Corners",
        "website":"http://www.crbc.us",
        "email":"",
        "pastor":" Bill Halliburton, Elder",
        "confession":"1689 Confessional",
        "lastUpdated":"5/28/2017"
    },
    {  
        "name":"Sovereign Grace Bible Church",
        "address":"2940 W Bethany Home Road, Phoenix AZ 85017",
        "lat":"33.52433",
        "long":"-112.122974",
        "region":"Arizona, Phoenix",
        "website":"http://sovgracephoenix.com/",
        "email":"",
        "pastor":"Dan Caffese, John Tock",
        "confession":"1689 Confessional (with some revisions)",
        "lastUpdated":"5/29/2017"
    },
    {  
        "name":"Texarkana Reformed Baptist",
        "address":"1801 South State Line, Texarkana, AR 71854",
        "lat":"33.404032",
        "long":"-94.043113",
        "region":"Arkansas, Texarkana",
        "website":"http://www.texarkanarbc.org/",
        "email":"",
        "pastor":"Martin Rizley",
        "confession":"1689 Confessional",
        "lastUpdated":"5/29/2017"
    },
    {  
        "name":"Igreja Batista Historica",
        "address":"Rua Jose Coelho 600, Conselheiro Lafaiete - MG, Brazil",
        "lat":"-20.651425",
        "long":"-43.803602",
        "region":"Brazil",
        "website":"https://igrejabatistahistorica.wordpress.com",
        "email":"ibhlafaiete@gmail.com",
        "pastor":"Daniel Deeds",
        "confession":"1689 Confessional",
        "lastUpdated":"5/29/2017"
    },
    {  
        "name":"Abounding Grace Church",
        "address":"St. Paul's School, 6101 W. Goshen Ave., Visalia, CA",
        "lat":"36.340887",
        "long":"-119.35887",
        "region":"California, Visalia",
        "website":"http://www.agcvisalia.org/",
        "email":"abouncinggracechurch@gmail.com",
        "pastor":"Jathan Newton",
        "confession":"1689 Confessional (essential agreement)",
        "lastUpdated":"5/29/2017"
    },
    {  
        "name":"Cornerstone Bible Church",
        "address":"114 Gemstone St., Ridgecrest, CA 93555",
        "lat":"35.621442",
        "long":"-117.667673",
        "region":"California, RIdgecrest",
        "website":"http://cbcridgecrest.org/",
        "email":"lynwrc@gmail.com",
        "pastor":"Lyn Whitcomb",
        "confession":"1689 Confessional",
        "lastUpdated":"5/29/2017"
    },
    {  
        "name":"Faith Community Church",
        "address":"723 South D. Street, Oxnard, CA 93030",
        "lat":"34.194362",
        "long":"-119.183099",
        "region":"California, Exnard",
        "website":"http://www.fccoxnard.org/",
        "email":"webservant@fccoxnard.org",
        "pastor":"Rick ANderson",
        "confession":"1689 Confessional",
        "lastUpdated":"5/29/2017"
    },
    {  
        "name":"Grace Baptist Church",
        "address":"37112 2nd Street, Fremont, CA 94536",
        "lat":"37.577352",
        "long":"-121.984501",
        "region":"California, Fremont",
        "website":"http://www.gracebaptist.ws/",
        "email":"",
        "pastor":"Micihael Phillips",
        "confession":"",
        "lastUpdated":"5/29/2017"
    },
    {  
        "name":"Grace Bible Church of Moorpark",
        "address":"12039 Hertz Street, Moorpark, CA 93021",
        "lat":"34.2822",
        "long":"-118.894217",
        "region":"California, Moorpark",
        "website":"http://www.gbcmpk.org/",
        "email":"errol.gbc@gmail.com",
        "pastor":"Errol Hale",
        "confession":"1689 Confessional",
        "lastUpdated":"5/29/2017"
    },
    {  
        "name":"Grace Bible Church",
        "address":"655 W. 11th Avenue, Escondido, CA 92025",
        "lat":"33.108451",
        "long":"-117.082644",
        "region":"California, Escondido",
        "website":"http://www.grcbible.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Grace Bible Church",
        "address":"7250 Eckstrom Ave, San Diego, CA 92111",
        "lat":"32.820591",
        "long":"-117.16449",
        "region":"California, San Diego",
        "website":"http://www.gbc-sd.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Heritage Valley Bible Church",
        "address":"461 Central Ave, Fillmore CA 93015",
        "lat":"34.40206",
        "long":"-118.914472",
        "region":"California, Fillmore",
        "website":"http://www.hvbible.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Providence Bible Church",
        "address":"709 Lakewood Drive, Sunnyvale CA 94089",
        "lat":"37.395217",
        "long":"-122.005515",
        "region":"California, Sunnyvale",
        "website":"http://www.pbc-ca.org/",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Reformed Baptist Church",
        "address":"7250 Mission Blvd, Riverside CA 92509",
        "lat":"34.011579",
        "long":"-117.441761",
        "region":"California, Riverside",
        "website":"http://rbcr.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Trinity Bible Church",
        "address":"7301 Highway 9, Felton CA 95018",
        "lat":"37.065358",
        "long":"-122.080269",
        "region":"California, Felton",
        "website":"http://www.tb-church.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Valley Center Community Church",
        "address":"29105 Valley Center Road, P.O. Box 130, Valley Center CA 92082",
        "lat":"33.230652",
        "long":"-117.026294",
        "region":"California, Valley Center",
        "website":"http://www.vccc.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Grace Community Church",
        "address":"150 Riverbrook Circle West, Lethbridge AB T1K7P",
        "lat":"49.661323",
        "long":"-112.869464",
        "region":"Canada, Lethbridge",
        "website":"http://www.lethbridgebaptist.com",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Sovereign Grace Baptist Church",
        "address":"Valley Christian School 8955 Cedar St, Mission BC V2V 5",
        "lat":"49.164636",
        "long":"-122.316001",
        "region":"Canada, Mission",
        "website":"http://www.sovereigngrace.bizland.com",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Squamish Baptist Church",
        "address":"2262 Read Crescent, Squamish BC",
        "lat":"49.735582",
        "long":"-123.123402",
        "region":"Canada, Squamish",
        "website":"http://www.squamishbaptistchurch.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Grace Bible Church",
        "address":"1350 Sage Ridge Road (P.O. Box 235), Meeker CO 81641",
        "lat":"40.054371",
        "long":"-107.909506",
        "region":"Colorado, Meeker",
        "website":"http://www.thescripturealone.com",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Northern Ridge Baptist",
        "address":"3100 Ridge View Dr., Erie CO 80516",
        "lat":"40.003652",
        "long":"-105.010897",
        "region":"Colorado, Erie",
        "website":"http://northernridge.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Providence Bible Church",
        "address":"1516 W. Prospect Road, Fort Collins CO 80526",
        "lat":"40.56775",
        "long":"-105.104426",
        "region":"Colorado, Fort Collins",
        "website":"http://www.providence-bible.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Shepherd's Community Church",
        "address":"505 Courtney Way, Lafayette CO 80026",
        "lat":"39.984301",
        "long":"-105.095651",
        "region":"Colorado, Lafayette",
        "website":"http://shepherds-church.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Southside Bible Church",
        "address":"7050 South Tucson Way, Centennial CO 80112",
        "lat":"39.588681",
        "long":"-104.834495",
        "region":"Colorado, Centennial",
        "website":"http://www.southsidebible.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Crosswalk Church",
        "address":"1016 Clearwater Road, Daytona Beach FL 32114",
        "lat":"29.180906",
        "long":"-81.030249",
        "region":"Florida, Daytona Beach",
        "website":"http://crosswalkdaytonabeach.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Orange Park Bible Church",
        "address":"505 Blanding Blvd., Orange Park FL 32073",
        "lat":"30.156537",
        "long":"-81.746129",
        "region":"Florida, Orange Park",
        "website":"http://www.opbiblechurch.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Sovereign Grace Family Church",
        "address":"13773 N. Main St., Jacksonville FL 32218",
        "lat":"30.486718",
        "long":"-81.625664",
        "region":"Florida, Jacksonville",
        "website":"http://www.SovereignGraceFamilyChurch.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Faith Bible Church",
        "address":"4907 Hwy 34 East, Sharpsburg GA 30277",
        "lat":"33.398688",
        "long":"-84.629838",
        "region":"Georgia, Sharpsburg",
        "website":"http://faithbiblechurch.us/",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Grace Community -North Georgia",
        "address":"1164 Couch Road, Dawsonville GA 30534",
        "lat":"34.367105",
        "long":"-84.019188",
        "region":"Georgia, Dawsonville",
        "website":"http://www.nourishedintheword.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Rockdale Community Church",
        "address":"2455 Old Salem Road, Conyers GA 30013",
        "lat":"33.623289",
        "long":"-83.997288",
        "region":"Georgia, Conyers",
        "website":"http://rockdalecommunitychurch.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Heritage of Grace Church",
        "address":"125 AA Road (Front), Columbia IL 62236",
        "lat":"38.48036",
        "long":"-90.219402",
        "region":"Illinois, Columbia",
        "website":"http://heritageofgrace.org/",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Living Hope Bible Church",
        "address":"6 N 171 Gary Ave., Roselle IL 60172",
        "lat":"41.966364",
        "long":"-88.120383",
        "region":"Illinois, Roselle",
        "website":"http://www.livinghopechurch.net",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Living Word Bible Church",
        "address":"304 East Jackson Street, Morris IL 60450",
        "lat":"41.360156",
        "long":"88.421521",
        "region":"Illinois, Morris",
        "website":"http://www.livingwordbible.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Christ Reformed Church",
        "address":"",
        "lat":"",
        "long":"",
        "region":"India, Secunderabad",
        "website":"http://thereformedtrust.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Nashik Baptist Church",
        "address":"Nashik Maharashtra",
        "lat":"19.997453",
        "long":"73.789802",
        "region":"INDIA, Nashik",
        "website":"http://nashikbaptist.com/",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Providence Evangelical Bible",
        "address":"Flat #38 6th Floor Daffodil CHS Godrej Skygardens, Takka Panvel",
        "lat":"18.981608",
        "long":"73.120257",
        "region":"India, Takka Panvel",
        "website":"",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Cornerstone Reformed Church",
        "address":"6956 N 575 E, Franklin IN 46131",
        "lat":"39.581159",
        "long":"-85.995912",
        "region":"Indiana, Franklin",
        "website":"http://cornerstonereformed.org/",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"First Baptist Church",
        "address":"1010 E. 126th Street, Carmel IN 46033",
        "lat":"39.971981",
        "long":"-86.111528",
        "region":"Indiana, Carmel",
        "website":"http://www.fbccarmel.com",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"First Baptist Church",
        "address":"103 S. Indiana St.",
        "lat":"39.519637",
        "long":"-86.168803",
        "region":"Indiana, Delphi",
        "website":"",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Hancock Reformed Baptist",
        "address":"944 E. Davis Road, Greenfield IN 46140",
        "lat":"39.772746",
        "long":"-85.754043",
        "region":"Indiana, Greenfield",
        "website":"http://hancockreformedbaptist.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Voice in the Wilderness",
        "address":"",
        "lat":"",
        "long":"",
        "region":"Israel, Jerusalem",
        "website":"http://www.voice-wilderness.com",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Chiesa Sola Grazia",
        "address":"Via Marconii 4, Porto Mantovano 46047",
        "lat":"45.187007",
        "long":"10.78898",
        "region":"Italy, Porto Mantovano",
        "website":"http://www.chiesasolagrazia.it",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"IXL Baptist Church",
        "address":"32990 61st Road, Arkansas City KS 67005",
        "lat":"37.012823",
        "long":"-97.039553",
        "region":"Kansas, Arkansas",
        "website":"",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Sovereign Grace Fellowship",
        "address":"2021 Gause Blvd. East, Slidell LA 70461",
        "lat":"30.28523",
        "long":"89.739611",
        "region":"Louisiana, Slidell",
        "website":"http://sgfellowship.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Trinity Baptist Church",
        "address":"3142 Bert Kouns, Shreveport LA 71118",
        "lat":"32.402848",
        "long":"-93.820489",
        "region":"Louisiana, Shreveport",
        "website":"http://www.tbcshreveport.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"International Bible Fellowship",
        "address":"311, Bonne Terre, Vacoas-Phoenix",
        "lat":"-20.272566",
        "long":"57.518549",
        "region":"Mauritius, Vacoas-Phoenix",
        "website":"http://ibfellowship.com",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Assembly of Christians",
        "address":"3619 W. Sterns Road, Lambertville MI 48144 ",
        "lat":"41.748985",
        "long":"-83.631782",
        "region":"Michigan, Lambertville",
        "website":"",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Calvary Bible Church",
        "address":"380 Linden St., Rogers City MI 49779 ",
        "lat":"45.419734",
        "long":"-83.829743",
        "region":"Michigan, Rogers City",
        "website":"http://www.calvarybiblerogerscity.com",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Grace Bible Church",
        "address":"1600 Vine Street, St. Clair MI 48079 ",
        "lat":"42.830438",
        "long":"-82.500272",
        "region":"Michigan, St. Clair",
        "website":"http://www.gracebiblechurchsc.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Grace Community Church",
        "address":"3500 New Holland Street MI 49426 ",
        "lat":"42.855331",
        "long":"-85.867529",
        "region":"Michigan, Hudsonville",
        "website":"http://www.solagrace.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Bethany Bible Church",
        "address":"511 Eagle Lake Road, Big Lake MN 55309 ",
        "lat":"45.336626",
        "long":"-93.742295",
        "region":"Minnesota, Big Lke",
        "website":"http://www.bethanybiblemn.org/",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Lifespring Church",
        "address":"30 Hallett Ave, Crosby MN 56441 ",
        "lat":"46.481218",
        "long":"-93.950698",
        "region":"Minnesota, Crosby",
        "website":"http://visitlifespring.com",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Audubon Dr Bible Church",
        "address":"2601 Audubon Dr, Laurel MS 39441",
        "lat":"31.722461",
        "long":"-89.135356",
        "region":"Mississippi, Laurel",
        "website":"http://audubonchurch.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Covenant of Peace Church",
        "address":"13600 John Clark Rd, Gulfport MS 39503",
        "lat":"30.474815",
        "long":"-89.12031",
        "region":"Mississippi, Gulfpot",
        "website":"http://covenantofpeace.net/",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Providence Baptist Church",
        "address":"201 Morrison Dr, Clinton MS 39056",
        "lat":"32.334186",
        "long":"-90.307913",
        "region":"Mississippi, Clinton",
        "website":"http://providencechurchms.com",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Christ Fellowship of Kansas City",
        "address":"Parkville MO 64152",
        "lat":"39.205023",
        "long":"-94.707062",
        "region":"Missouri, Parkville (Kansas City)",
        "website":"http://www.christfellowshipkc.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Grace Community Church",
        "address":"2320 Heybourne Lane, Minden NV 89423",
        "lat":"39.007401",
        "long":"-119.763411",
        "region":"Nevada, Minden",
        "website":"http://gracenevada.com",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Providence Reformed Church",
        "address":"3157 N. Rainbow Blvd, Las Vegas NV 89108-4578",
        "lat":"36.217389",
        "long":"-115.244903",
        "region":"Nevada, Las Vegas",
        "website":"http://provref.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"First Baptist Church",
        "address":"232 Main St, Matawan NJ 07747",
        "lat":"40.410608",
        "long":"-74.233653",
        "region":"New Jersey, Matawan",
        "website":"http://fbcmatawan.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Church of the Redeemer",
        "address":"1715 Hwy 314 NW, Los Lunas NM 87031",
        "lat":"34.827068",
        "long":"-106.73205",
        "region":"New Mexico, Los Lunas",
        "website":"http://churchoftheredeemerll.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Clarkson Community Church",
        "address":"8339 W. Ridge Road, Brockport NY 14420",
        "lat":"43.232168",
        "long":"-77.926119",
        "region":"New York, Brockport",
        "website":"http://www.clarksonchurch.com",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Evangelical Church Fairport",
        "address":"38 East Church Street, Fairport NY 14450",
        "lat":"43.098202",
        "long":"-77.439195",
        "region":"New York, Fairport",
        "website":"http://www.ecfnet.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Grace Fellowship",
        "address":"25 Sullivan Ave, Port Jervis NY 12771",
        "lat":"41.378689",
        "long":"-74.685841",
        "region":"New York, Port Jervis",
        "website":"http://www.graceinport.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Living Faith Baptist Church",
        "address":"8600 Hood Road, Charlotte NC 28215",
        "lat":"35.259373",
        "long":"-80.6895",
        "region":"North Carolina, Charlotte",
        "website":"http://livingfaithbc.net/",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Cornerstone Bible Church",
        "address":"45 W. Church St., Xenia OH 45385",
        "lat":"39.686854",
        "long":"-83.930529",
        "region":"Ohio, Xenia",
        "website":"http://www.cbcxenia.com",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Cornerstone Bible Fellowship",
        "address":"36300 Center Ridge Road, North Ridgeville OH 44039",
        "lat":"41.38987",
        "long":"-82.022527",
        "region":"Ohio, North Ridgeville",
        "website":"http://www.cbfministry.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Grace Covenant Church",
        "address":"780 N Fairfield Rd, Beavercreek OH 45434",
        "lat":"39.712397",
        "long":"-84.061761",
        "region":"Ohio, Beavercreek",
        "website":"http://www.gccbeavercreek.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"LaRue Baptist Church",
        "address":"217 N High St, LaRue OH 43332",
        "lat":"40.579061",
        "long":"-83.384746",
        "region":"Ohio, LaRue",
        "website":"http://www.laruebaptist.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Redeemer Covenant Church",
        "address":"400 Powell Drive, Arlington OH 45814",
        "lat":"40.888604",
        "long":"-83.661781",
        "region":"Ohio, Arlington",
        "website":"http://redeemercovenantarlington.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Northwest Bible Church",
        "address":"4301 NW 36th, Oklahoma City OK 73112",
        "lat":"35.508136",
        "long":"-97.597242",
        "region":"Oklahoma, Oklahoma City",
        "website":"http://www.nwbcokc.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Shawnee Bible Church",
        "address":"2100 E 45th, Shawnee OK 74804",
        "lat":"35.37675",
        "long":"-96.896033",
        "region":"Oklahoma, Shawnee",
        "website":"http://shawneebible.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Sovereign Grace Baptist",
        "address":"2120 W. Pine, Enid OK 73703",
        "lat":"36.401201",
        "long":"97.9044",
        "region":"Oklahoma, Enld",
        "website":"http://sgbcenid.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Sovereign Grace Bible Church",
        "address":"317 W. Main St., Ada OK 74821",
        "lat":"34.774512",
        "long":"-96.682199",
        "region":"Oklahoma, Ada",
        "website":"http://www.sgbca.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Grace Fellowship Baptist",
        "address":"10333 Greenwood Road, Huntingdon PA 16652",
        "lat":"40.618876",
        "long":"-77.922645",
        "region":"Pennsylvania, Huntingdon",
        "website":"http://www.gracereformedbaptist.com",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Pine Creek Church",
        "address":"865 State Route 28 & 66, Kittanning PA",
        "lat":"40.798888",
        "long":"-79.492603",
        "region":"Pennsylvania, Kittanning",
        "website":"http://www.pinecreekchurch.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Reformed Baptist of Scranton",
        "address":"114 Hill Street, Scranton PA 18512",
        "lat":"41.418708",
        "long":"-75.619701",
        "region":"Pennsylvania, Scranton",
        "website":"",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Travelers Rest Community Church",
        "address":"940 Mush Creek Road, Travelers Rest SC 29690",
        "lat":"35.047144",
        "long":"-82.382024",
        "region":"South Carolina, Travelers Rest",
        "website":"http://www.livinggracesc.com",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Iglesia Evangelica de la Gracia",
        "address":"Carrer de l'Abat Odó, 20, Barcelona 08030, Spain",
        "lat":"41.432354",
        "long":"2.188194",
        "region":"Spain, Barcelona",
        "website":"http://www.porGracia.es",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Calvary Community Church",
        "address":"1537 Dalton Street, Alcoa TN 37701",
        "lat":"35.798602",
        "long":"-83.977138",
        "region":"Tennessee, Louisville",
        "website":"http://ccctn.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Grace Baptist Church",
        "address":"550 McMurry Blvd E, Hartsville TN 37074",
        "lat":"36.392897",
        "long":"-86.151878",
        "region":"Tennessee, Hartsville",
        "website":"http://www.gracebaptisthartsville.com",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Grace Bible Fellowship",
        "address":"10905 Lebanon Road, Mount Juliet TN 37122",
        "lat":"36.231027",
        "long":"-86.507225",
        "region":"Tennessee, Mount Juliet",
        "website":"http://gracemountjuliet.com",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Trinity Reformed Baptist",
        "address":"6771 Stage Road, Bartlett TN 38134",
        "lat":"35.205374",
        "long":"-89.837794",
        "region":"Tennessee, Bartlett",
        "website":"http://www.trbcmemphis.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Good Shepherd Community",
        "address":"4701 Virginia Ave., Dallas TX 75228",
        "lat":"32.80354",
        "long":"-96.775887",
        "region":"Texas, Dallas",
        "website":"http://www.gsccdallas.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Grace Bible Chapel",
        "address":"18911 Redland Road, San Antonio TX 78259",
        "lat":"29.615908",
        "long":"-98.451926",
        "region":"Texas, San Antonio",
        "website":"http://www.gbcsa.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Killeen Bible Church",
        "address":"4717 Westcliff Road, Killeen TX 76543",
        "lat":"31.122962",
        "long":"-97.673439",
        "region":"Texas, Killeen",
        "website":"http://killeenbible.org/",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Providence Church",
        "address":"101 Albemarle Road, Marshall TX 75672",
        "lat":"32.524075",
        "long":"-94.367234",
        "region":"Texas, Marshall",
        "website":"",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Providence Church",
        "address":"4101 E Park Blvd, Plano TX 75074",
        "lat":"33.032678",
        "long":"-96.649482",
        "region":"Texas, Plano",
        "website":"http://www.providencechurch.info",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Cunupia Bible Church",
        "address":"Longdenville Old Road & Ragoonanan Road, Chaguanas, Trinidad & Tobago",
        "lat":"10.530439",
        "long":"-61.37578",
        "region":"Trinidad, Enterprise",
        "website":"",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Reformed Evangelical Church",
        "address":"90 Tunapuna Road, Tunapuna, Trinidad & Tobago",
        "lat":"10.651865",
        "long":"-61.390979",
        "region":"Trinidad, Tunapuna",
        "website":"http://rec-tt.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Roy Bible Church",
        "address":"5757 South 3100 West, Roy UT 84067",
        "lat":"41.15884",
        "long":"-112.054964",
        "region":"Utah, Roy",
        "website":"http://roybiblechurch.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Reformed Bible Church",
        "address":"894 VT-133, West Rutland VT 05777",
        "lat":"43.562969",
        "long":"-73.032455",
        "region":"Vermont, Rutland",
        "website":"http://www.allbygrace.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Iglesia Biblica de la Gracia",
        "address":"5912 Franconia Road, Alexandria VA 22310",
        "lat":"38.784419",
        "long":"-77.137469",
        "region":"Virginia, Alexandria",
        "website":"http://ibdg.org/",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Grace Evangelical Church",
        "address":"1411 Wieldraayer Rd, Oak Harbor WA 98277",
        "lat":"48.296455",
        "long":"-122.69198",
        "region":"Washington, Oak Harbor",
        "website":"http://www.graceevangelical.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Juanita Community Church",
        "address":"10007 NE 132nd Street, Kirkland WA 98034",
        "lat":"47.718058",
        "long":"-122.206893",
        "region":"Washington, Kirkland",
        "website":"http://juanitacc.com",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Peninsula Bible Church",
        "address":"3520 Edgewood Drive, Port Angeles WA 98362",
        "lat":"48.112344",
        "long":"-123.530164",
        "region":"Washington, Port Angeles",
        "website":"http://www.peninsulabiblechurch.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Providence Family Baptist",
        "address":"2609 Larch Way, Lynnwood WA 98036",
        "lat":"47.811413",
        "long":"-122.2687",
        "region":"Washington, Lynnwood",
        "website":"http://www.providencefbc.org",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    },
    {  
        "name":"Trinity BIble Church",
        "address":"535 S Evarts, Powell WY 82435",
        "lat":"44.747819",
        "long":"-108.753124",
        "region":"Wyoming, Powell",
        "website":"http://tbcwyoming.com",
        "email":"",
        "pastor":"",
        "confession":"",
        "lastUpdated":"6/2/2017 (in progress)"
    }
];